---
abstract: 'Access Matplotlib from Perl; providing consistent user interface between different plot types'
author:
  - 'David E. Condon <dec986@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Matplotlib-Simple
requires:
  Capture::Tiny: '0'
  Data::Printer: '0'
  Devel::Confess: '0'
  Devel::Size: '0'
  Test::More: '0'
  perl: '5.008'
version: '0.03'
x_generated_by_perl: v5.42.0
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
